apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
     app: mywp
spec:
 containers:
 - name: con1
   image: wordpress:latest
   ports:
   - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mywp-svc
spec:
   type: LoadBalancer
   selector:
     app: mywp
   ports:
   - port: 80

